version: "3.9"
services:
  selenium:
    container_name: selenium_firefox
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
